### ISSUE TITLE
Couldn't resolve module/action in ansible-lint action

### ISSUE THREAD

**Issue by solairen** [ansible/ansible-lint-action#133] opened 2022-10-15 08:41 UTC
Hi,

I have a problem with the ansible-lint action. 
When I use it locally in my project:
```bash
ansible-lint
```
everything works correctly. No errors, or issues.

However, when I use it on my GitHub Actions there are errors:
```log
Error: couldn't resolve module/action 'ansible.builtin.aws_s3'. This often indicates a misspelling, missing collection, or incorrect module path.
Error: couldn't resolve module/action 'ansible.builtin.docker_network'. This often indicates a misspelling, missing collection, or incorrect module path.
Error: couldn't resolve module/action 'ansible.builtin.aws_s3'. This often indicates a misspelling, missing collection, or incorrect module path.
```

Are there missing some modules in `ansible-lint-actions`? 
I do not use any external modules. All modules are from `builtin`.

**Comment by AirOnSkin** [comment] 2022-10-17 05:46
I think AWS modules are part of the community.aws bundle -> https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_s3_module.html
In this case this would mean `ansible.builtin.aws_s3` -> `amazon.aws.aws_s3 module`

docker_network is part of the community.docker bundle -> https://docs.ansible.com/ansible/latest/collections/community/docker/docker_network_module.html#ansible-collections-community-docker-docker-network-module
That would mean `ansible.builtin.docker_network` -> `community.docker.docker_network`

**Comment by solairen** [comment] 2022-10-17 18:05
Yes, they are.
So this need to be installed inside the Github Action workflow? 
I did not install it locally and the `ansible-lint` works fine on my PC.

**Comment by AirOnSkin** [comment] 2022-10-18 06:50
@solairen Have you tried just changing the module reference and running the linter again on GitHub?
We also use modules from community collections and it works out of the box with the GH action. No need to install anything ...

**Comment by solairen** [comment] 2022-10-18 09:04
I will try it.

**Comment by maxbirkner** [comment] 2022-11-25 10:32
I had the same issue in one of my Ansible projects and was able to fix it by adding the affected module to a _collections/requirements.yml_ file. For example:

```
---
collections:
- name: community.general
  version: 5.8.0

**Comment by gl72** [comment] 2022-12-14 09:30
Hello there, I am having the same issue with the module ansible.posix, I installed the collection on the runner and added the requirements.yml in the collections folder but I am still facing the same error. Do you have any idea on how to solve this?
The runner has Ansible 2.11 installed.
Thanks!

**Comment by ssbarnea** [comment] 2022-12-24 20:00
@gl72 If you add `requirements.yml` to repository root it should work.

**Comment by ssbarnea** [comment] 2022-12-25 14:04
I am going to close this ticket because the original report is not a bug but more lack of knowledge that `ansible.builtin.aws_s3` and all the other ones are no longer builtins since... few years back.

**Closed by ssbarnea** 2022-12-25 14:04 UTC
