### ISSUE TITLE
add option to test against older ansible versions

### ISSUE THREAD

**Issue by ahmadalli** [ansible/ansible-lint-action#19] opened 2020-03-29 13:56 UTC
is it possible to test a playbook with older ansible versions and make sure the playlist is compatible with them or not? for example `exit_host` is added to ansible 2.8's `meta` module and fails on older ansible versions

**Comment by webknjaz** [comment] 2020-04-02 22:27
You're basically asking for the possibility to install extra packages in the container in runtime.

I think it's a duplicate of #8

**Closed by webknjaz** 2020-04-02 22:27 UTC

**Comment by xUnholy** [comment] 2020-04-02 22:35
@ahmadalli there is a pull request that would allow you to test with pinned versions #17 

While this PR is pending I've got a forked version with this capability here: https://github.com/xUnholy/ansible-lint-action

**Comment by ahmadalli** [comment] 2020-04-03 08:32
@xUnholy thanks :)

**Comment by webknjaz** [comment] 2020-04-04 00:22
@ahmadalli that's now in master.

**Comment by ahmadalli** [comment] 2020-04-04 07:36
thanks :)

**Comment by ahmadalli** [comment] 2020-04-04 07:36
thanks :)
